#+TITLE: Information and Strategy
#+AUTHOR: Christoph Schottmüller
#+Options: toc:nil H:2
#+Latex_Header: \usepackage{natbib}

* News
- This website will be slowly updated over the coming weeks to give students information about the course "Information and Strategy".
- Lecture time and place in WS 2019/20: Tuesday and Thursday 16:00-17:30 (103/S82)

* Description
This course deals with information economics. That is, how to people and/or organizations strategically interact that have access to different information sources? We also deal with the natural follow up question: Who will and/ or should have access to what information and what kind of information can/will/should be transmitted from one person to another? 

There are numerous applications from all fields of economics. These cover classic questions, like: how will a firm design its pricing schedule, e.g. quantity discounts, if it does not know the willingness to pay of its customers? But also modern questions, e.g. "how does the internet change the way in which people communicate and obtain information, say, about politics?" or "to what extent should, so called, stress tests by the banking supervisors reveal information about default risks of banks?".   

The course uses mainly game theoretic models in order to shed light on questions similar to those above. Methodologically, students get to know the basic models of information economics (screening, cheap talk, information design etc.). This will enable students to read research papers in which these tools are used. 

** Objective
The course has various goals. First, students get to know the blockbuster ideas in information economics and learn how to use these in order to gain insights into various economic problems. Second, students learn how to read research papers. The latter skill tends to be useful when working on seminar papers or a thesis. The former tends to be useful in life and work.

** Grading

Grading is based on a presentation and a written report. Both the presentation and the report are on a research paper in information economics. The main task is to summarizes the paper and (mainly in the written report) to briefly evaluate the paper, discuss it or comment on it. The page limit for the report is 6 pages. Note that this course is not a so-called "Seminar". The main difference to a seminar is that (i) the majority of the course consists of lectures, (ii) you do not have to produce an own original contribution in the report and consequently the report is shorter than a typical seminar paper. 

If a student prefers to write a research proposal instead of a report, this is possible as well.

Presentations have to be in English. Reports can be written in English or German.

Attendance is voluntary and does not affect the grading of your report directly. (Of course, the lectures are intended to prepare you for writing a good report and that would constitute an indirect effect.) 

** Plan

A preliminary plan can be found [[https://github.com/schottmueller/infoStrat/blob/master/plan.org][here]]. (A less often updated pdf with properly formatted references is available [[https://github.com/schottmueller/infoStrat/files/3381859/plan.pdf][here]].)

The structure of the course is as follows: In the first part of the course, there will mainly be lectures on information economics and its applications. However, we will have a few "practice sessions" in which we discuss a paper that all students should have read/skimmed before. These sessions add to the material of the lecture but are also meant to give you some practice in "how to read a paper (quickly)," i.e. these sessions prepare students for their presentations and reports. The second (and shorter) part of the course consists of student presentations of papers in information economics.

* Course material
** Lecture material
- [[https://github.com/schottmueller/infoStrat/files/3615206/htrap.pdf][guide]] on how to read a paper

** Books
Some of the lectures are based on parts of books. Noteworthy are
- Bolton P. and Dewatripont M., "Contract theory", MIT Press 2005,
- Campbell D.E., "Incentives: motivation and the economics of information", Cambridge University Press 2018.

For more specific reading material and references to research papers, check the course [[https://github.com/schottmueller/infoStrat/files/3381859/plan.pdf][plan]].
