#+TITLE: Information and Strategy
#+AUTHOR: Christoph Schottmüller
#+Options: toc:nil H:2
#+Latex_Header: \usepackage{natbib}

This plan is preliminary and subject to changes.

* Introduction to asymmetric information

We use the first 2-3 weeks to introduce the classics in information economics. We see that asymmetric information can lead to inefficiencies in markets and start to discuss what measures players/markets may use to avoid these inefficiencies (at least partially). However, we also see that the clever use of information asymmetries can make everyone better off in some cases. 

** Akerlof's lemons market
- Akerlof's lemons market
- the first welfare theorem does not hold if different players have different information 
- applications: used car markets and warranties, adverse selection in insurance markets
- reading: chapter 5.3 in cite:campbell2018incentives
** Mediation and correlated equilibrium
- correlated equilibrium
- an impartial mediator can use asymmetric information to make everyone better off
- reading for the technical details: chapter 8 in cite:maschler2013game
** Information rents and screening
- 2 type screening problem and revelation principle
- information creates "rents" for those who have information but uninformed parties reduce these rents by distorting allocations inefficiently
- applications: non-linear pricing by a monopolist, credit rationing
- technical extension: screening with a continuum of types
- reading: chapter 2.1.3, 2.2.1 and 2.3.3 in  cite:bolton2005contract

* Information design
Sometimes we can determine how informed others (or we ourselves) will be, e.g. a central bank can decide how to test banks in a "stress test" (and the information the market gets from the test depends on how strict the test is), a prosecutor decides which witnesses to hear in court and a school might decide how finely grained its grade system is. Which design should the information designer optimally choose?
** Bayesian persuasion
- Bayesian persuasion and the concavification approach
- how can you structure other players' information to reach your goals?
- application: will bad banks fail optimal stress tests?
- reading: cite:kamenica11_bayes_persuas
** Bilateral trade
- consumer surplus maximizing information structures
- how much information about a product do you want to have before buying it?
- application: "strategic ignorance"
- reading: cite:roe17
** Bayes correlated equilibrium
- the BCE approach to information design
- reading: section 1-3.2 in cite:bergemann19_infor_desig

* Strategic communication
People might share what they know with others. The recipients of the information might be able to make use of this information when choosing what to do; e.g. you might go to a new restaurant if someone tells you it is great. This, however, opens the door for manipulation: For example, the restaurant owner might pay people to give positive reviews to others. Which sender and which messages can be trusted to what extent?
** Homophily and echo chambers
- discrete state cheap talk
- People mainly communicate with people that are similar to them. Is this inefficient or could there be an informational reason?
- application: communication and the internet, echo chambers
- reading: cite:jann2018echo
** Continuous state
- classic cheap talk model with a continuum of states
- applications: delegation
- reading: cite:crawford1982cheap

* Presenting evidence
Sometimes one can communicate information credibly by having a third party expert certifying it; e.g. rating agencies can certify the quality of an asset or the creditworthiness of a person, one can take a test - like GRE or TOEFL - to certify certain abilities etc. Who will certify what? Which information will be transmitted and which won't?
** complete unraveling
- the incentive to show that one is better than the rest can lead to complete information
- applications: privacy legislation
- reading: ch. 5.1 in cite:bolton2005contract, (background: cite:milgrom1981good)
** partial unravelling
- costly certification and noisy certification (Dye's model)
- who will certify if the unravelling logic does not apply completely?
- applications: should students be able to choose among exam questions?, risk taking (BDL) 
- reading: [[https://sites.google.com/site/eddiedekelsite/pres_address_2016_slides/pres_address_2016_slides.pdf?attredirects=0&d=1][Dekel's slides]], (background: cite:dye1985disclosure,jung1988disclosure)
** certification
cite:strausz2005honest,stahl2017certification 

* Social learning
If you are interested in what others know, it is usually best to observe what they do. Consequently, economic agents are often learning from observing the behavior of others; e.g. investors learn from how other investors invest, politicians learn from voting behavior, firms infer information about market conditions from the behavior of competitors etc. This learning behavior can, however, have unintended consequences if agents rely too much on others and too little on their own information. In this case "informational cascades" can occur in which everyone takes the same - and possibly wrong - action. 

** Herd behavior
cite:banerjee1992simple,smith2000pathological

 cite:bikhchandani1992theory

* Reputation and advice
** Chain store paradox and reputation
**  Career concerns
Holmstrøm
** advice
cite:ottaviani2006professional

# * Technical tools
# Understanding research papers requires to know certain tools and techniques. The following pop up quite often in information economics papers.
# ** Screening with a continuum of types
# ** Value of information

# * Information acquisition

# * Global games

# * Experimentation

* Papers to present
These are some papers that students may choose to present. If you want to present a paper that is not on the list, please contact the course instructor.

** Information design
- cite:condorelli2017information
- cite:taneva2018information
- cite:bergemann16_bayes_correl_equil_compar_infor_struc_games
- cite:bergemann17_first_price_auction_with_gener_infor_struc
- cite:bergemann2015limits
- cite:ely2017beeps
- cite:baliga2016torture

** Hard evidence
- cite:demarzo2018test
- cite:song2003disclosures
- cite:ben2014optimal

** Cheap talk
- cite:farrell1989cheap
- cite:stein1989cheap
- cite:alonso2008does
- cite:dessein2002authority
- cite:schottmueller2013cifd
- cite:galeotti2013strategic
- cite:kartik2009strategic
- cite:hagenbach2010strategic
- cite:austensmith20001

** Social learning
- cite:caplin1994business
- cite:gale1996have

# ** Information acquisition
# - cite:burke2012information Banks search for information about the creditworthiness of consumers. Is the amount of search welfare optimal? What is the market outcome if firms can (not) price discriminate?
# - cite:armstrong2009consumer Analyzes the impact of consumer protection policy on the incentives of consumers to become informed and shows some surprising unintended consequences of consumer protection rules.
** Reputation and advice
- cite:prendergast1993theory
- cite:prat2005wrong


bibliographystyle:chicago
bibliography:/home/christoph/stuff/bibliography/references.bib
